version: '2'
services:
    myapp-app:
        image: myapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://myapp-postgresql:5432/myApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myapp-postgresql:
        extends:
            file: postgresql.yml
            service: myapp-postgresql
